### ISSUE TITLE
AR Simulation hybrid AR/3D scene problem

### ISSUE THREAD

**Issue by Scrantch** [needle-tools/ar-simulation#49]
Using ARS but now have a hybrid AR/Non-AR scene. Meaning I need to start and stop AR and go between a regular 3D scene and an AR scene. I’m having a hard time debugging this with ARS active. I have 2 cameras one for AR and one for regular. I deactivate all the AR nodes (session, session origin, etc) and AR camera and activate the regular camera. I also use XRGeneralSettings.Instance.Manager.StopSubsystems() to stop all AR subsystems when switching to regular mode. But yet, ARS still seems to be active and screwing with things. Also, it highjacks the regular 3D camera and keeps changing the Culling Mask on it so none of my objects (on different named layers) show up in the Game View. 

So first, need ARS to stop grabbing my non AR camera and messing with it. And second, how can I turn ARS on and off so I can switch between these two modes of the app? It seems that ARS should respect me turning off XR subsystems right?

 - Unity 2021.1.13f1
 - ARFoundation 4.1.1
 - OS: Mac
 - ARSimulation 1.2.0

Thank you.

**Comment by marwie** [comment]
Hello @Scrantch 

Thanks for reporting this issue.

It is odd that ARSimulation does fiddle with your other camera. Can you send me a small repro of this issue? 
ARS should only ever use the position of the camera assigned to the SessionOrigin. 

Do you use Device Simulator and does it happen only with DS or also normal Game Mode?

ARS should respect subsystems being turned off, that's right.

**Comment by marwie** [comment]
Hey @Scrantch I just looked at the code. I think you've found a bug, because currently the ARS loader can't be stopped. I'm working on a fix.

**Comment by marwie** [comment]
Hello @Scrantch 
We've just released version 1.2.0-preview.1. Please try if the fix helps with your project and let me know how it goes!

**Comment by Scrantch** [comment]
Great! Thanks for the super fast turnaround. Can you give guidance on the proper way to shut it down?

**Comment by marwie** [comment]
The method you've been using should work in Editor or disabling all the ARFoundation components when you switch to your other app mode (internally they stop the corresponding subsystem on OnDisable)

**Comment by marwie** [comment]
Hello @Scrantch did you try the new version?

**Comment by Scrantch** [comment]
Hi sorry for the delay. Got sidetracked. So, no, this is still not working. Are you guys changing the camera Culling Mask for any reason? Like for the Simulated Environment? Something is still grabbing my regular camera (when the AR camera is off) and messing with those settings so my content doesn't show up. Again, I make a call XRGeneralSettings.Instance.Manager.StopSubsystems() and I have also just disabled ARS in XR Management Project Settings as well as deactivated Simulation AR Environment Manager in the scene. But yet, I still warning messages from ARS that no ARSession found and "using main camera." Why would that still be happening if everything is off? 
<img width="823" alt="Screen Shot 2021-02-17 at 9 59 26 AM" src="https://user-images.githubusercontent.com/60194745/108247222-3900de00-7107-11eb-88a9-8969466ef2b9.png">

**Comment by marwie** [comment]
Thanks for getting back.

The warning will be logged the first time anyone tries to find the ARCamera (in this case the EnvironmentManager inspector). You're right, it shouldnt be printed if ARS wasnt enabled. I will fix that.

We're changing the culling mask for environment simulation, yes. I found one spot were setting the culling mask was wrong and it might be the reason for your issue (it is also the only spot the culling mask is changed on the ARCamera).  See below ``ARCamera.cullingMask``.

![image](https://user-images.githubusercontent.com/5083203/108335494-526f5c00-71d3-11eb-9bb2-c99ad68a5235.png)

I have changed the code in ``SimulatedAREnvironmentManager`` to this, could you try if that **does** fix it for you?

![image](https://user-images.githubusercontent.com/5083203/108335594-6f0b9400-71d3-11eb-90e6-299896930f86.png)

**Comment by marwie** [comment]
Can you try ``1.0.2-preview.2`` ?

**Comment by Scrantch** [comment]
That did it! Still get the warning message but now it's not highjacking the camera anymore. Still need to test when the code will switch back and forth between AR and regular 3D mode so will let you know how that goes in the next couple days. Still not quite there yet. Thank you!

**Comment by Scrantch** [comment]
OK, finally got the back and forth between regular 3D and AR integrated. However, it doesn't appear to be working with ARS. The game starts in regular 3D mode. When I flip the switch it enters AR mode by using the following StartXR code:

`    public IEnumerator StartXR()
    {
        Debug.Log("Initializing XR...");
        yield return XRGeneralSettings.Instance.Manager.InitializeLoader();

        if (XRGeneralSettings.Instance.Manager.activeLoader == null)
        {
            Debug.LogError("Initializing XR Failed. Check Editor or Player log for details.");
        }
        else
        {
            Debug.Log("Starting XR...");
            ARCamera.gameObject.SetActive(true);

            XRGeneralSettings.Instance.Manager.StartSubsystems();

            TogglePlaneDetection(true);
        }
    }

    void StopXR()
    {
        Debug.Log("Stopping XR...");


        XRGeneralSettings.Instance.Manager.StopSubsystems();
        XRGeneralSettings.Instance.Manager.DeinitializeLoader();
        Debug.Log("XR stopped completely.");

            ARCamera.gameObject.SetActive(false);
    }`

It also disables the regular 3D camera. When we flip back it does the opposite and enables the regular 3D camera and calls the StopXR code above. When I do this in editor and flip to AR mode I get a completely pink Game View screen (except for UI) but I can move the AR camera around with the ARS keyboard controls. 

When I flip back to regular 3D the Game View resumes and I can see through the regular camera. If I flip back to AR again, we get the pink screen and also this time the keyboard controls to move the camera don't work. How can I get ARS to play nicely? Is there some init or reset routines I'm missing? Please advise.

Thanks,

Grant

**Comment by Scrantch** [comment]
Here's a shot where you can actually see through the AR camera in the Scene view inset but totally pink in Game View:

<img width="887" alt="Screen Shot 2021-02-25 at 4 14 40 PM" src="https://user-images.githubusercontent.com/60194745/109236539-a86c7280-7784-11eb-8ae8-f89b4ef02aa0.png">

**Comment by marwie** [comment]
@Scrantch could you upload and send me the project to look into? It would help a lot with understanding and finding the issue :)

**Comment by Scrantch** [comment]
Unfortunately I cannot for security reasons. Forbidden. :(

**Comment by Scrantch** [comment]
Any logs anywhere or anything like that I can send you? Didn't get any errors or out of bounds warnings in the console.

**Comment by marwie** [comment]
I see. Do you think you could reproduce it in an isolated project? I'll try as well.

Some more questions:
1) Are you using URP?
2) Is the SimulatedAREnvironmentManager active in the scene?
3) Could you send me the code for ``TogglePlaneDetection``  as well? Does it just toggle the plane manager?
4) When switching are you just enabling/disabling the camera component or the whole gameobject or even Session/SessionOrigin?

**Comment by Scrantch** [comment]
When I flip to AR mode I can, for an instant, see through the AR camera in Game View before it throughs up the pink screen. Also, I notice one of the components you put on the camera has a pink main light color. My lights were never pink. Could this be related? Blasting everything out? 

<img width="393" alt="Screen Shot 2021-02-25 at 4 46 55 PM" src="https://user-images.githubusercontent.com/60194745/109238827-1450da00-7789-11eb-8e97-06d7290c3966.png">

**Comment by marwie** [comment]
> When I flip to AR mode I can, for an instant, see through the AR camera in Game View before it throughs up the pink screen. Also, I notice one of the components you put on the camera has a pink main light color. My lights were never pink. Could this be related? Blasting everything out?
> 
> <img alt="Screen Shot 2021-02-25 at 4 46 55 PM" width="393" src="https://user-images.githubusercontent.com/60194745/109238827-1450da00-7789-11eb-8e97-06d7290c3966.png">

interesting. Which light is used as "Input Light" here? 
Your scene does look very bright as well. Maybe that's the reason for that?
Are you using Light Estimation as well?

**Comment by Scrantch** [comment]
> I see. Do you think you could reproduce it in an isolated project? I'll try as well.
> 
> Some more questions:
> 
> 1. Are you using URP?
> 2. Is the SimulatedAREnvironmentManager active in the scene?
> 3. Could you send me the code for `TogglePlaneDetection`  as well? Does it just toggle the plane manager?
> 4. When switching are you just enabling/disabling the camera component or the whole gameobject or even Session/SessionOrigin?

1. Not using URP (though we will be soon). Using builtin for the moment. 
2. Yes SimAREnvManager is active (this is never turned off when switching, should it?). Also Sim AR Env Instance and Sim AR Env Camera are in the scene but greyed out.
3. See below for TogglePlane code
4. When switching, I'm turning off the whole camera game object with SetActive. Vice versa for both AR and regular 3D cameras. Not disabling Session/Origin because I assume the start/stop code is doing all of that.

`    public void TogglePlaneDetection(bool on)
    {
        // arPlaneManager.enabled = on;
        if (on)
            arPlaneManager.planePrefab = arPlaneManagerPrefab;
        else
            arPlaneManager.planePrefab = null;

        arPlaneManager.SetTrackablesActive(on);
    }
`

**Comment by Scrantch** [comment]
> > When I flip to AR mode I can, for an instant, see through the AR camera in Game View before it throughs up the pink screen. Also, I notice one of the components you put on the camera has a pink main light color. My lights were never pink. Could this be related? Blasting everything out?
> > <img alt="Screen Shot 2021-02-25 at 4 46 55 PM" width="393" src="https://user-images.githubusercontent.com/60194745/109238827-1450da00-7789-11eb-8e97-06d7290c3966.png">
> 
> interesting. Which light is used as "Input Light" here?
> Your scene does look very bright as well. Maybe that's the reason for that?
> Are you using Light Estimation as well?

The Input Light is something you guys create, no? It links to one of your nodes in the scene. Yes, using light estimation. Fooling around with all any of the lights or parameters or values in all of these doesn't change it a bit though. Still totally pink in Game View. Isn't this Unity's way of complaining about the camera or shaders or something? I feel like it's something you guys are doing with the camera. Related to the start of this thread perhaps?

**Comment by hybridherbst** [comment]
We really want to help and get this fixed - but it's hard to see from the screenshots and description what's going on here. 

Please try to reproduce in a separate project and send us that project - that'll certainly be the fastest way to get this fixed.
Additionally, we're happy to sign an NDA in case that allows you to send over the original project. You can reach out via hi@needle.tools or send a DM in our support discord so it stays private.

Thank you!

**Comment by Scrantch** [comment]
OK was able to make a sandbox project. Just emailed you guys so let me know where to put it. Thanks!

**Comment by marwie** [comment]
Resolved in ``1.2.0-preview.4``
